""" Output from the feedparser.feed method, with results returned as a list. """

[{'title': 'VA strengthens care for Veterans impacted by intimate partner violence and sexual assault',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': 'VA strengthens care for Veterans impacted by intimate partner violence and sexual assault'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5747'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5747',
  'summary': 'The Department of Veterans Affairs recently initiated a pilot program to improve services for Veterans who have experienced or are experiencing intimate partner violence or sexual assault.',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': 'The Department of Veterans Affairs recently initiated a pilot program to improve services for Veterans who have experienced or are experiencing intimate partner violence or sexual assault.'},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5747',
  'guidislink': False,
  'published': 'Tue, 14 Dec 2021 16:00:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=12, tm_mday=14, tm_hour=21, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=348, tm_isdst=0)},
 {'title': "2021 Under Secretary for Health's Robert L. Jesse Award recognizes VA boundary-breaking innovations",
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': "2021 Under Secretary for Health's Robert L. Jesse Award recognizes VA boundary-breaking innovations"},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5746'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5746',
  'summary': 'The Department of Veterans Affairs honored three innovative health care practices and their creators late October with the Robert L. Jesse Award for Excellence in Innovation.',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': 'The Department of Veterans Affairs honored three innovative health care practices and their creators late October with the Robert L. Jesse Award for Excellence in Innovation.'},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5746',
  'guidislink': False,
  'published': 'Wed, 8 Dec 2021 10:07:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=12, tm_mday=8, tm_hour=15, tm_min=7, tm_sec=0, tm_wday=2, tm_yday=342, tm_isdst=0)},
 {'title': 'VA advances Electronic Health Record Modernization program',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': 'VA advances Electronic Health Record Modernization program'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5745'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5745',
  'summary': 'The Department of Veterans Affairs announced today its updated plan to move forward with its systemwide Electronic Health Record Modernization program.',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': 'The Department of Veterans Affairs announced today its updated plan to move forward with its systemwide Electronic Health Record Modernization program.'},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5745',
  'guidislink': False,
  'published': 'Wed, 1 Dec 2021 12:52:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=12, tm_mday=1, tm_hour=17, tm_min=52, tm_sec=0, tm_wday=2, tm_yday=335, tm_isdst=0)},
 {'title': 'VA statement on GPO printing and mailing delay',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': 'VA statement on GPO printing and mailing delay'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5744'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5744',
  'summary': 'Due to supply chain and staffing shortages, the vendor contracted by the Government Publishing Office to provide printing services for the Department of Veterans Affairs is experiencing delays in printing and mailing notification letters to Veterans and claimants. The disruption may impact the ability of some claimants to meet required deadlines via written correspondence with VA.',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': 'Due to supply chain and staffing shortages, the vendor contracted by the Government Publishing Office to provide printing services for the Department of Veterans Affairs is experiencing delays in printing and mailing notification letters to Veterans and claimants. The disruption may impact the ability of some claimants to meet required deadlines via written correspondence with VA.'},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5744',
  'guidislink': False,
  'published': 'Tue, 30 Nov 2021 14:10:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=11, tm_mday=30, tm_hour=19, tm_min=10, tm_sec=0, tm_wday=1, tm_yday=334, tm_isdst=0)},
 {'title': 'VA and Indian Health Service broaden scope to serve American Indian and Alaska Native Veterans',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': 'VA and Indian Health Service broaden scope to serve American Indian and Alaska Native Veterans'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5743'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5743',
  'summary': "The Department of Veterans Affairs and the Indian Health Service renewed a partnership, Oct. 1, to help the country's nearly 145,000 American Indian and Alaska Native Veterans overcome health care access barriers.",
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': "The Department of Veterans Affairs and the Indian Health Service renewed a partnership, Oct. 1, to help the country's nearly 145,000 American Indian and Alaska Native Veterans overcome health care access barriers."},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5743',
  'guidislink': False,
  'published': 'Tue, 23 Nov 2021 11:34:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=11, tm_mday=23, tm_hour=16, tm_min=34, tm_sec=0, tm_wday=1, tm_yday=327, tm_isdst=0)},
 {'title': 'Smoking rates steadily trend down among Veterans receiving VA care',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': 'Smoking rates steadily trend down among Veterans receiving VA care'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5742'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5742',
  'summary': 'In conjunction with the Great American Smokeout observed Nov. 18, the Department of Veterans Affairs is encouraging Veterans to talk to their health care providers about smoking cessation programs to help them quit, as cigarette use continues to decline nationwide.',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': 'In conjunction with the Great American Smokeout observed Nov. 18, the Department of Veterans Affairs is encouraging Veterans to talk to their health care providers about smoking cessation programs to help them quit, as cigarette use continues to decline nationwide.'},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5742',
  'guidislink': False,
  'published': 'Thu, 18 Nov 2021 11:07:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=11, tm_mday=18, tm_hour=16, tm_min=7, tm_sec=0, tm_wday=3, tm_yday=322, tm_isdst=0)},
 {'title': 'VA helps women Veteran entrepreneurs power up',
  'title_detail': {'type': 'text/plain',
   'language': None,
   'base': '',
   'value': 'VA helps women Veteran entrepreneurs power up'},
  'links': [{'rel': 'alternate',
    'type': 'text/html',
    'href': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5741'}],
  'link': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5741',
  'summary': 'The Department of Veterans Affairs, in collaboration with the PenFed Foundation, helped three women-owned small businesses earn business development grants used to support their growing companies in the economic marketplace.',
  'summary_detail': {'type': 'text/html',
   'language': None,
   'base': '',
   'value': 'The Department of Veterans Affairs, in collaboration with the PenFed Foundation, helped three women-owned small businesses earn business development grants used to support their growing companies in the economic marketplace.'},
  'id': 'https://www.va.gov/opa/pressrel/PressArtInternet.cfm?id=5741',
  'guidislink': False,
  'published': 'Tue, 16 Nov 2021 10:16:00 EST',
  'published_parsed': time.struct_time(tm_year=2021, tm_mon=11, tm_mday=16, tm_hour=15, tm_min=16, tm_sec=0, tm_wday=1, tm_yday=320, tm_isdst=0)}]